"""
Send run summaries via SMTP (Gmail and most providers).

Set secrets with environment variables (recommended):
  SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, EMAIL_TO

Or fill values in Config.py (avoid committing passwords).
"""

from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email.message import EmailMessage
from typing import Iterable, Optional


def _cfg(name: str, default: str = "") -> str:
    v = os.environ.get(name)
    if v is not None and str(v).strip():
        return str(v).strip()
    return default


def send_smtp_email(
    subject: str,
    body: str,
    *,
    to_addrs: Optional[Iterable[str]] = None,
) -> tuple[bool, str]:
    """
    Send a plain-text email. Returns (success, message).

    Configuration is read from environment first, then Config.
    """
    try:
        from Config import (
            EMAIL,
            EMAIL_FROM,
            EMAIL_TO,
            SMTP_HOST,
            SMTP_PASSWORD,
            SMTP_PORT,
            SMTP_USE_TLS,
            SMTP_USER,
        )
    except ImportError:
        return False, "Config module not found."

    host = _cfg("SMTP_HOST", SMTP_HOST)
    port_str = _cfg("SMTP_PORT", str(SMTP_PORT))
    try:
        port = int(port_str)
    except ValueError:
        port = 587
    user = _cfg("SMTP_USER", SMTP_USER)
    password = _cfg("SMTP_PASSWORD", SMTP_PASSWORD)
    from_addr = _cfg("EMAIL_FROM", EMAIL_FROM) or user
    cfg_to = (EMAIL_TO or "").strip()
    env_to = _cfg("EMAIL_TO", "")
    default_to = env_to or cfg_to or (EMAIL or "").strip()

    if "SMTP_USE_TLS" in os.environ:
        use_tls = os.environ.get("SMTP_USE_TLS", "1").lower() in ("1", "true", "yes")
    else:
        use_tls = bool(SMTP_USE_TLS)

    recipients = list(to_addrs) if to_addrs else []
    if not recipients:
        if default_to:
            recipients = [default_to]
        else:
            return False, "No recipient: set EMAIL_TO or EMAIL in Config, or environment EMAIL_TO."

    if not host or not user or not password:
        return (
            False,
            "SMTP not configured: set SMTP_HOST, SMTP_USER, SMTP_PASSWORD (and EMAIL_TO). "
            "For Gmail use an App Password and smtp.gmail.com:587.",
        )
    if not from_addr:
        from_addr = user

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(recipients)
    msg.set_content(body)

    try:
        with smtplib.SMTP(host, port, timeout=30) as smtp:
            if use_tls:
                smtp.starttls()
            smtp.login(user, password)
            smtp.send_message(msg)
        return True, f"Email sent to {', '.join(recipients)}"
    except Exception as exc:
        return False, f"SMTP error: {exc}"


def format_run_report(
    *,
    keyword: str,
    location: str,
    top_jobs_lines: str,
    auto_apply_lines: str = "",
    notes: str = "",
) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    parts = [
        f"Job analyzer run - {ts}",
        "",
        f"Search: keyword={keyword!r}  location={location}",
        "",
        "--- Top jobs ---",
        top_jobs_lines or "(none)",
        "",
    ]
    if auto_apply_lines.strip():
        parts.extend(["--- LinkedIn Easy Apply assist ---", auto_apply_lines.strip(), ""])
    if notes.strip():
        parts.extend([notes.strip(), ""])
    parts.append("This message was generated by main.py (job analyzer).")
    return "\n".join(parts)
